"""
action_task.py — Persistent record of an action execution request.

Lifecycle
---------
  pending    → task created, not yet picked up by an agent or operator
  executing  → an agent or operator has claimed the task (atomic via FOR UPDATE)
  done       → completed successfully (agent wrote result_detail)
  failed     → execution attempted, terminal error (result_detail has reason)
  dismissed  → merchant or system dismissed without executing

One task per (shop_domain, product_url, action_type) in a non-terminal
state.  The executor service enforces this at write time — if a pending
or executing task already exists for the triple, it is returned instead
of creating a duplicate.

source_candidate
    The full candidate dict from generate_action_candidates() that
    triggered this task.  Stored verbatim so AI agents have full context
    without re-querying the pipeline.

task_payload
    Generated by action_executor.build_payload().  Structure is
    action_type-specific:

triggered_by
    "manual"         — merchant clicked Execute in the dashboard
    "auto"           — system policy triggered execution automatically
    <agent_id>       — specific AI agent that created the task

claimed_by
    NULL             — task not yet claimed
    <agent_id>       — the agent instance that set status to executing
    Written atomically with SELECT FOR UPDATE during the claim transition.
    Enables crash detection and future stale-task recovery.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import Column, DateTime, Float, Index, Integer, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB

from app.core.database import Base
from app.core.time_utils import utc_now_naive


class ActionTask(Base):
    __tablename__ = "action_tasks"

    id = Column(Integer, primary_key=True)

    shop_domain = Column(String, nullable=False)
    product_url = Column(String, nullable=False)   # canonical /products/{handle}
    action_type = Column(String, nullable=False)   # SCARCITY_NUDGE | PRICE_TEST | …

    # Lifecycle state — see module docstring.
    status = Column(String, nullable=False, default="pending", server_default="pending")

    # Who or what created this task.
    triggered_by = Column(String, nullable=False, default="manual", server_default="manual")

    # Which agent instance claimed this task (set atomically with FOR UPDATE).
    # NULL = unclaimed.
    claimed_by = Column(String, nullable=True)

    # Full candidate dict that triggered this task — stored for agent context.
    source_candidate = Column(JSONB, nullable=False)

    # Generated execution payload — checklist, fixes, automation hint.
    task_payload = Column(JSONB, nullable=False)

    # Key scoring fields from the candidate — indexed for prioritization queries.
    expected_loss = Column(Float, nullable=True)
    confidence    = Column(Float, nullable=True)
    urgency       = Column(Float, nullable=True)

    created_at   = Column(DateTime, nullable=False, default=utc_now_naive, server_default=text("now()"))
    updated_at   = Column(DateTime, nullable=False, default=utc_now_naive, server_default=text("now()"), onupdate=utc_now_naive)
    executed_at  = Column(DateTime, nullable=True)   # set when status → executing
    completed_at = Column(DateTime, nullable=True)   # set when status → done | failed | dismissed

    # Agent output, completion note, or terminal error message.
    result_detail = Column(Text, nullable=True)

    __table_args__ = (
        # Fast per-shop task listing
        Index("ix_action_tasks_shop_domain", "shop_domain"),
        # Fast queue reads for agents: WHERE status = 'pending'
        Index("ix_action_tasks_status", "status"),
        # Composite: per-shop pending queue (most common agent query)
        Index("ix_action_tasks_shop_status", "shop_domain", "status"),
    )
