"""
EvolutionProposal — self-improvement proposals generated by the evolution engine.

risk_level: LEVEL_1 (safe auto-apply) | LEVEL_2 (PR + human) | LEVEL_3 (proposal only)
status: open | accepted | rejected | applied | expired
        | obsolete | resolved_indirectly | needs_revalidation   (GC lifecycle)
"""
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Float, Integer, String, Text, Index, Boolean

from app.core.database import Base

# All valid statuses — used for validation in GC and API
VALID_STATUSES = {
    "open", "accepted", "rejected", "applied", "expired",
    "obsolete", "resolved_indirectly", "needs_revalidation",
}

# Statuses that the GC may transition proposals INTO
GC_STATUSES = {"obsolete", "resolved_indirectly", "needs_revalidation"}

# Statuses that GC is allowed to transition FROM (only open proposals are GC targets)
GC_SOURCE_STATUSES = {"open"}

# Statuses that block the evolution engine from recreating a proposal with the
# same dedup_key.  "needs_revalidation" is included because it means "still
# under review" — the operator hasn't cleared it yet, so recreating would loop.
ENGINE_DEDUP_STATUSES = {"open", "accepted", "needs_revalidation"}


def _now_utc():
    return datetime.now(timezone.utc).replace(tzinfo=None)


class EvolutionProposal(Base):
    __tablename__ = "evolution_proposals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, nullable=False, default=_now_utc)
    proposal_type = Column(String(32), nullable=False)     # refactor | reliability | performance | security
    target_file = Column(String(256), nullable=True)
    risk_level = Column(String(16), nullable=False)        # LEVEL_1 | LEVEL_2 | LEVEL_3
    reason = Column(Text, nullable=False)
    expected_impact = Column(Text, nullable=True)
    auto_applicable = Column(Boolean, nullable=False, default=False, server_default="false")
    status = Column(String(32), nullable=False, default="open", server_default="open")
    decided_by = Column(String(128), nullable=True)
    decided_at = Column(DateTime, nullable=True)
    audit_cycle = Column(String(32), nullable=True)        # e.g. "2026-W13"
    dedup_key = Column(String(256), nullable=True)         # prevents duplicate proposals

    # Reviewer link
    reviewer_assessment_id = Column(Integer, nullable=True)

    # GC lifecycle metadata
    gc_reason = Column(Text, nullable=True)                # human-readable explanation of GC transition
    gc_updated_at = Column(DateTime, nullable=True)        # when GC last changed this proposal's status

    # Closed-loop outcome tracking (populated by evolution_proposal_outcomes)
    linked_bugfix_candidate_id = Column(Integer, nullable=True)
    applied_at = Column(DateTime, nullable=True)
    applied_commit_sha = Column(String(64), nullable=True)
    outcome_status = Column(String(32), nullable=True)     # effective | ineffective | inconclusive
    outcome_measured_at = Column(DateTime, nullable=True)
    outcome_evidence = Column(Text, nullable=True)

    # Business outcome tracking (populated by evolution_business_outcomes)
    business_outcome = Column(String(32), nullable=True)   # improved | declined | stable | inconclusive | not_applicable | pending
    business_measured_at = Column(DateTime, nullable=True)
    business_evidence = Column(Text, nullable=True)

    # Decision engine fields
    confidence_score = Column(Float, nullable=True)
    decision_status = Column(String(32), nullable=True)
    decision_decided_at = Column(DateTime, nullable=True)
    rollback_candidate_id = Column(Integer, nullable=True)

    # Strategic bet fields
    affected_shop_domains = Column(Text, nullable=True)
    affected_product_urls = Column(Text, nullable=True)
    affected_files = Column(Text, nullable=True)
    linked_nudge_ids = Column(Text, nullable=True)
    extended_from_proposal_id = Column(Integer, nullable=True)
    revenue_thesis = Column(Text, nullable=True)
    rejected_alternatives = Column(Text, nullable=True)
    infra_cost_estimate = Column(String(32), nullable=True)
    exploration_bet = Column(Boolean, nullable=True)

    # UX/governance fields
    ux_sensitive = Column(Boolean, nullable=True)
    impact_radius = Column(String(32), nullable=True)
    strategy_alignment_score = Column(Float, nullable=True)
    strategy_version = Column(Integer, nullable=True)

    # Learning isolation: classifies the evidence environment.
    # pre_merchant | internal_test | sandbox | real_merchant
    evidence_source = Column(String(32), nullable=True, default="pre_merchant")

    __table_args__ = (
        Index("ix_evolution_proposals_status", "status", "created_at"),
        Index("ix_evolution_proposals_dedup", "dedup_key"),
        Index("ix_evolution_proposals_business_outcome", "business_outcome", "business_measured_at"),
        Index("ix_evolution_proposals_decision", "decision_status", "decision_decided_at"),
        Index("ix_evolution_proposals_extended_from", "extended_from_proposal_id"),
        Index("ix_evolution_proposals_linked_bugfix", "linked_bugfix_candidate_id"),
        Index("ix_evolution_proposals_outcome", "outcome_status", "outcome_measured_at"),
    )
