"""
EvolutionProposal — self-improvement proposals generated by the evolution engine.

risk_level: LEVEL_1 (safe auto-apply) | LEVEL_2 (PR + human) | LEVEL_3 (proposal only)
status: open | accepted | rejected | applied | expired
        | obsolete | resolved_indirectly | needs_revalidation   (GC lifecycle)
"""
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Integer, String, Text, Index, Boolean

from app.core.database import Base

# All valid statuses — used for validation in GC and API
VALID_STATUSES = {
    "open", "accepted", "rejected", "applied", "expired",
    "obsolete", "resolved_indirectly", "needs_revalidation",
}

# Statuses that the GC may transition proposals INTO
GC_STATUSES = {"obsolete", "resolved_indirectly", "needs_revalidation"}

# Statuses that GC is allowed to transition FROM (only open proposals are GC targets)
GC_SOURCE_STATUSES = {"open"}

# Statuses that block the evolution engine from recreating a proposal with the
# same dedup_key.  "needs_revalidation" is included because it means "still
# under review" — the operator hasn't cleared it yet, so recreating would loop.
ENGINE_DEDUP_STATUSES = {"open", "accepted", "needs_revalidation"}


def _now_utc():
    return datetime.now(timezone.utc).replace(tzinfo=None)


class EvolutionProposal(Base):
    __tablename__ = "evolution_proposals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, nullable=False, default=_now_utc)
    proposal_type = Column(String(32), nullable=False)     # refactor | reliability | performance | security
    target_file = Column(String(256), nullable=True)
    risk_level = Column(String(16), nullable=False)        # LEVEL_1 | LEVEL_2 | LEVEL_3
    reason = Column(Text, nullable=False)
    expected_impact = Column(Text, nullable=True)
    auto_applicable = Column(Boolean, nullable=False, default=False)
    status = Column(String(32), nullable=False, default="open")
    decided_by = Column(String(128), nullable=True)
    decided_at = Column(DateTime, nullable=True)
    audit_cycle = Column(String(32), nullable=True)        # e.g. "2026-W13"
    dedup_key = Column(String(256), nullable=True)         # prevents duplicate proposals

    # Reviewer link
    reviewer_assessment_id = Column(Integer, nullable=True)

    # GC lifecycle metadata
    gc_reason = Column(Text, nullable=True)                # human-readable explanation of GC transition
    gc_updated_at = Column(DateTime, nullable=True)        # when GC last changed this proposal's status

    __table_args__ = (
        Index("ix_evolution_proposals_status", "status", "created_at"),
        Index("ix_evolution_proposals_dedup", "dedup_key"),
    )
