#!/usr/bin/env bash
# install_hooks.sh — wire preflight.sh into .git/hooks/pre-commit
#
# Run once after cloning the repo. Safe to re-run — overwrites the hook.
#
# Usage:  bash backend/scripts/install_hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"
PREFLIGHT="backend/scripts/preflight.sh"

if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "install_hooks: not a git repository root ($REPO_ROOT)" >&2
    exit 1
fi

chmod +x "$REPO_ROOT/backend/scripts/preflight.sh"

cat > "$HOOK" <<EOF
#!/usr/bin/env bash
# Auto-generated by backend/scripts/install_hooks.sh
# Runs backend/scripts/preflight.sh before every commit.
# Bypass with \`git commit --no-verify\` if absolutely necessary.
exec "\$(git rev-parse --show-toplevel)/$PREFLIGHT"
EOF

chmod +x "$HOOK"
echo "install_hooks: pre-commit hook installed at $HOOK"
echo "install_hooks: will run $PREFLIGHT on every git commit"
