#!/usr/bin/env bash
# install_hooks.sh — wire preflight + TIER_0 auto-deploy hooks.
#
# Run once after cloning the repo. Safe to re-run — overwrites hooks.
#
# Installs:
#   pre-commit   → backend/scripts/preflight.sh (31 audits)
#   post-commit  → backend/scripts/post_commit_auto_deploy.sh
#                  (TIER_0 auto-deploy per Phase 1.9.5)
#
# Usage:  bash backend/scripts/install_hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PRE_HOOK="$REPO_ROOT/.git/hooks/pre-commit"
POST_HOOK="$REPO_ROOT/.git/hooks/post-commit"
PREFLIGHT="backend/scripts/preflight.sh"
AUTO_DEPLOY="backend/scripts/post_commit_auto_deploy.sh"

if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "install_hooks: not a git repository root ($REPO_ROOT)" >&2
    exit 1
fi

chmod +x "$REPO_ROOT/$PREFLIGHT"
chmod +x "$REPO_ROOT/$AUTO_DEPLOY"
chmod +x "$REPO_ROOT/backend/scripts/classify_commit_tier.py"

# --- pre-commit ---
cat > "$PRE_HOOK" <<EOF
#!/usr/bin/env bash
# Auto-generated by backend/scripts/install_hooks.sh
# Runs backend/scripts/preflight.sh before every commit.
# Bypass with \`git commit --no-verify\` if absolutely necessary.
exec "\$(git rev-parse --show-toplevel)/$PREFLIGHT"
EOF
chmod +x "$PRE_HOOK"

# --- post-commit ---
cat > "$POST_HOOK" <<EOF
#!/usr/bin/env bash
# Auto-generated by backend/scripts/install_hooks.sh
# Runs backend/scripts/post_commit_auto_deploy.sh after every commit.
# Classifies the commit (TIER_0/1/2) and auto-deploys only TIER_0.
# Opt-out per-commit: HS_NO_AUTO_DEPLOY=1 git commit -m "..."
exec "\$(git rev-parse --show-toplevel)/$AUTO_DEPLOY"
EOF
chmod +x "$POST_HOOK"

echo "install_hooks: pre-commit  → $PREFLIGHT"
echo "install_hooks: post-commit → $AUTO_DEPLOY (TIER_0 auto-deploy)"
