"""
segment_monitor_worker.py — Proactive hot-segment action task + nudge creation.

Responsibility
--------------
Every cycle (default: 5 minutes), scan all active Pro shops for products
whose hot audience segment has crossed actionable thresholds.  When a
revenue window is open:
  1. Create (or dedup) a SCARCITY_NUDGE action task.
  2. Create (or refresh) an ActiveNudge — the storefront delivery artifact
     that spark-nudge.js polls to render real nudges on product pages.

This gives WishSpark a fully closed loop:
  behavioral data → empirical segment → task creation → live nudge delivery

Cycle
-----
  1. Query active Pro merchants (plan='pro' AND billing_active=true).
  2. For each Pro shop: find products with recent visitor activity from
     product_metrics (unique_visitors_24h >= MIN_ACTIVE_VISITORS_24H).
  3. For each active product: call segment_product_visitors() to compute the
     hot segment state for the last HOT_SEGMENT_WINDOW_HOURS.
  4. If hot.visitor_count >= MIN_HOT_VISITORS AND
        hot.estimated_revenue_window >= MIN_REVENUE_WINDOW:
       a. Check cooldown: skip task creation if a SCARCITY_NUDGE task was
          completed (done/failed/dismissed) within COOLDOWN_HOURS.
       b. Call create_task() — the executor's dedup handles the pending/
          executing case without a second check here.
       c. ALWAYS call create_or_refresh_nudge() when conditions are met —
          even on a task dedup hit.  This keeps the nudge TTL fresh and
          updates visitor_count/revenue_window to the latest scan data.
  5. Write a WorkerLog row for each cycle.
  6. Sleep SLEEP_SECONDS.

Deduplication strategy
-----------------------
Task dedup (two-layer):

  Active guard (handled by create_task):
    If a SCARCITY_NUDGE task for the same (shop, product, action_type) is
    already pending or executing, create_task() returns it unchanged.

  Cooldown guard (handled by _has_cooldown_task):
    If a SCARCITY_NUDGE task triggered by this worker was completed in the
    last COOLDOWN_HOURS, skip task creation entirely.

Nudge dedup (handled by create_or_refresh_nudge):
  If an active, non-expired nudge already exists for (shop, product,
  action_type), it is refreshed (expires_at extended, visitor_count updated)
  rather than replaced.  This ensures exactly one active nudge per product
  at all times while keeping the storefront copy current.

Nudge lifecycle
---------------
The nudge TTL (NUDGE_TTL_HOURS = 4) acts as a dead-man's switch:
  - While hot conditions persist: worker refreshes the nudge every 5 min,
    extending expires_at → nudge stays live indefinitely.
  - When conditions fall below threshold: worker stops refreshing.
    The nudge ages out in at most 4 hours without any explicit deletion.
  - The aggregation_worker sweeps expired nudges (status → 'expired')
    on every 5-minute cycle.

This means nudges are always self-healing:
  - No hot conditions → nudge naturally expires.
  - Hot conditions return → new nudge is created on the next cycle.
  - Hot conditions persist → nudge is continuously refreshed.

Action type selection
---------------------
SCARCITY_NUDGE is used for all hot-segment triggers:
  - Most lightweight intervention (social proof, interest signal).
  - Does not require discounting or inventory data.
  - Copy is fully truthful (grounded in real behavioral segment counts).

FLASH_INCENTIVE (discount code) is not auto-generated by this worker.
Discounting is a merchant decision requiring explicit approval.
"""
from __future__ import annotations

import logging
log = logging.getLogger("segment_monitor_worker")
import sys
import time
from datetime import datetime, timedelta, timezone

sys.path.append("/opt/wishspark/backend")

from app.core.env_bootstrap import load_env
load_env()

from app.core.sentry_init import init_sentry, cron_monitor
init_sentry(component="segment_monitor_worker")

from app.core.logging_config import configure_logging, set_worker_context
configure_logging()
set_worker_context(worker_name="segment_monitor_worker")

from sqlalchemy import text
from sqlalchemy.orm import Session, sessionmaker

from app.core.database import engine
from app.models.action_task import ActionTask
from app.models.merchant import Merchant
from app.models.worker_log import WorkerLog
from app.models.worker_state import WorkerState
from app.services.action_executor import create_task
from app.services.audience_segments import segment_product_visitors
from app.services.nudge_engine import create_or_refresh_nudge
from app.services.shopify_admin import get_product_inventory

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

WORKER_NAME = "segment_monitor_worker"
SLEEP_SECONDS = 300              # 5 minutes between cycles

# Per-cycle shop budget — at 10k Pro merchants a synchronous loop cannot
# finish within the 5-minute cycle. We process a bounded batch each cycle and
# use a Redis-backed cursor so the next cycle picks up where we left off,
# guaranteeing every shop gets scanned in at most
#   (total_shops / MAX_SHOPS_PER_CYCLE) * SLEEP_SECONDS
# wall-clock time. At 10k/500 = 20 cycles × 5min = 100min full-fleet coverage.
MAX_SHOPS_PER_CYCLE = 500
CYCLE_TIME_BUDGET_S = 240  # hard stop at 4min to guarantee heartbeat before 5min cycle

# Hot segment trigger thresholds
MIN_HOT_VISITORS = 3             # minimum hot visitor count to trigger
MIN_REVENUE_WINDOW = 50.0        # minimum estimated revenue window ($) to trigger

# Product scan filter — skip products with almost no traffic
MIN_ACTIVE_VISITORS_24H = 2      # product_metrics.unique_visitors_24h must be >= this

# After a task is completed (done/failed/dismissed), don't re-trigger for this long
COOLDOWN_HOURS = 4

# Segmentation window passed to segment_product_visitors()
HOT_SEGMENT_WINDOW_HOURS = 72

# Action type and trigger label
ACTION_TYPE  = "SCARCITY_NUDGE"
TRIGGERED_BY = "hot_segment_monitor"

# Below this inventory level we add scarcity copy to the nudge.
# Requires merchant to have a Shopify Admin API access_token stored.
# If the Shopify call fails, nudge is created without scarcity copy (non-fatal).
LOW_STOCK_THRESHOLD = 10


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

_log = logging.getLogger("worker.segment_monitor")

def log(msg: str) -> None:
    _log.info(msg)


# ---------------------------------------------------------------------------
# Pro shop discovery
# ---------------------------------------------------------------------------

def _get_pro_shops(db: Session) -> list[str]:
    """Return shop_domain list for all active Pro merchants (sorted for cursor stability)."""
    # Operator/dev tenant exclusion (founder direttiva 2026-05-06): the
    # founder's hedgespark-dev shop is plan=pro+billing_active=true,
    # but it must not be processed by the segment-monitoring cycle.
    from app.core.operator_blocklist import operator_dev_shops
    rows = (
        db.query(Merchant.shop_domain)
        .filter(
            Merchant.plan == "pro",
            Merchant.billing_active == True,  # noqa: E712
            ~Merchant.shop_domain.in_(operator_dev_shops()),
        )
        .order_by(Merchant.shop_domain.asc())
        .all()
    )
    return [r.shop_domain for r in rows]


_CURSOR_KEY = "hs:segmon:cursor"


def _load_cursor() -> int:
    try:
        from app.core.redis_client import _client
        rc = _client()
        if rc is None:
            from app.core.silent_fallback import record_silent_return
            record_silent_return("segment_monitor.load_cursor.redis_down")
            return 0
        v = rc.get(_CURSOR_KEY)
        return int(v) if v else 0
    except Exception as exc:
        _log.warning("segment_monitor_worker: _load_cursor failed: %s", exc)
        return 0


def _save_cursor(pos: int) -> None:
    try:
        from app.core.redis_client import _client
        rc = _client()
        if rc is None:
            from app.core.silent_fallback import record_silent_return
            record_silent_return("segment_monitor.save_cursor.redis_down")
            return
        rc.set(_CURSOR_KEY, str(pos), ex=86400)
    except Exception as exc:
        _log.warning("segment_monitor_worker: _save_cursor failed: %s", exc)


def _batch_for_cycle(all_shops: list[str]) -> tuple[list[str], int]:
    """Slice the shop list into this cycle's batch using a round-robin cursor.

    Returns (batch, next_cursor_position). At <= MAX_SHOPS_PER_CYCLE shops
    total, this returns the entire list every cycle (no batching needed).
    """
    if len(all_shops) <= MAX_SHOPS_PER_CYCLE:
        return all_shops, 0
    start = _load_cursor() % len(all_shops)
    end = start + MAX_SHOPS_PER_CYCLE
    if end <= len(all_shops):
        batch = all_shops[start:end]
        next_pos = end % len(all_shops)
    else:
        # Wrap around
        batch = all_shops[start:] + all_shops[: end - len(all_shops)]
        next_pos = end - len(all_shops)
    return batch, next_pos


# ---------------------------------------------------------------------------
# Active product discovery (uses pre-aggregated product_metrics)
# ---------------------------------------------------------------------------

def _get_active_products_for_shop(db: Session, shop_domain: str) -> list[str]:
    """
    Return product_url list for products with sufficient recent visitor traffic.

    Reads from product_metrics (pre-aggregated by aggregation_worker every 5 min)
    rather than scanning events directly, for speed.  Products below
    MIN_ACTIVE_VISITORS_24H are not worth computing a full segment report for.

    Returns empty list on any error — non-fatal.
    """
    try:
        result = db.execute(
            text("""
                SELECT product_url
                FROM product_metrics
                WHERE shop_domain       = :shop
                  AND unique_visitors_24h >= :min_visitors
                ORDER BY unique_visitors_24h DESC
            """),
            {"shop": shop_domain, "min_visitors": MIN_ACTIVE_VISITORS_24H},
        )
        return [row.product_url for row in result.fetchall()]
    except Exception as exc:
        log(f"active-products query error shop={shop_domain}: {exc}")
        return []


# ---------------------------------------------------------------------------
# Cooldown guard — prevents task re-trigger after recent completion
# ---------------------------------------------------------------------------

def _has_cooldown_task(
    db:          Session,
    shop_domain: str,
    product_url: str,
) -> bool:
    """
    Return True if a hot-segment-monitor SCARCITY_NUDGE task for this
    (shop, product) was completed within the last COOLDOWN_HOURS.

    Terminal tasks (done / failed / dismissed) that completed within the
    cooldown window block re-creation.  Active tasks (pending / executing)
    are handled separately by create_task() dedup — not checked here.
    """
    cooldown_cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(hours=COOLDOWN_HOURS)
    existing = (
        db.query(ActionTask)
        .filter(
            ActionTask.shop_domain == shop_domain,
            ActionTask.product_url == product_url,
            ActionTask.action_type == ACTION_TYPE,
            ActionTask.triggered_by == TRIGGERED_BY,
            ActionTask.status.in_(["done", "failed", "dismissed"]),
            ActionTask.completed_at >= cooldown_cutoff,
        )
        .first()
    )
    return existing is not None


# ---------------------------------------------------------------------------
# Per-product processing — the core loop body
# ---------------------------------------------------------------------------

def _process_product(
    db:          Session,
    shop_domain: str,
    product_url: str,
) -> str:
    """
    Evaluate one product's hot segment state and create/refresh a
    SCARCITY_NUDGE task and ActiveNudge when all conditions are satisfied.

    Nudge creation/refresh is decoupled from task dedup:
      - Task: created once, deduped until done/failed/dismissed
      - Nudge: refreshed on EVERY qualifying cycle to keep visitor_count
        and expires_at current, regardless of whether the task is new or old

    Returns a status string for the cycle summary:
      "created"         — new task AND nudge created
      "refreshed"       — task deduped (existing active), nudge refreshed
      "cooldown"        — task in cooldown, nudge NOT refreshed
      "below_threshold" — hot segment present but below visitor/revenue minimum
      "no_hot_visitors" — hot segment is empty
      "error"           — exception during computation
    """
    # 1. Compute hot segment state
    try:
        report = segment_product_visitors(
            db=db,
            shop_domain=shop_domain,
            product_url=product_url,
            hours=HOT_SEGMENT_WINDOW_HOURS,
        )
    except Exception as exc:
        log(f"segment query error shop={shop_domain} product={product_url}: {exc}")
        return "error"

    hot  = report.get("hot", {})
    meta = report.get("meta", {})

    visitor_count     = int(hot.get("visitor_count", 0))
    revenue_window    = float(hot.get("estimated_revenue_window", 0.0))
    avg_bi            = hot.get("avg_behavioral_index")
    cvr_estimate      = hot.get("cvr_estimate")
    calibration_state = meta.get("calibration_state", "unknown")

    # 2. Gate: no hot visitors
    if visitor_count == 0:
        return "no_hot_visitors"

    # 3. Gate: below thresholds
    if visitor_count < MIN_HOT_VISITORS or revenue_window < MIN_REVENUE_WINDOW:
        log(
            f"below_threshold shop={shop_domain} product={product_url} "
            f"hot_visitors={visitor_count} revenue_window=${revenue_window:.2f} "
            f"(need >= {MIN_HOT_VISITORS} visitors AND >= ${MIN_REVENUE_WINDOW:.0f})"
        )
        return "below_threshold"

    # 4. Cooldown guard — applies only to task creation, not nudge refresh
    in_cooldown = _has_cooldown_task(db, shop_domain, product_url)
    if in_cooldown:
        log(
            f"cooldown hit shop={shop_domain} product={product_url} "
            f"— terminal {ACTION_TYPE} task exists within last {COOLDOWN_HOURS}h "
            f"(nudge also NOT refreshed during cooldown)"
        )
        return "cooldown"

    # 5. Fetch real inventory from Shopify Admin API (optional enrichment).
    #    Only called after all gates pass — conserves Shopify API rate limit quota.
    #    Failure is non-fatal: nudge creation continues with inventory_count=None,
    #    which means no scarcity copy (truthfulness rule: never fake scarcity).
    inventory_count: int | None = None
    try:
        inv = get_product_inventory(db, shop_domain, product_url)
        if inv is not None:
            inventory_count = inv.get("inventory_quantity")
            log(
                f"inventory shop={shop_domain} product={product_url} "
                f"qty={inventory_count} title={inv.get('title', '?')!r}"
            )
    except Exception as exc:
        log(f"inventory fetch error shop={shop_domain} product={product_url}: {exc} (non-fatal)")

    # 6. Build candidate dict for task creation
    urgency = round(min(1.0, visitor_count / 20.0), 4)
    candidate = {
        "action_type":              ACTION_TYPE,
        "product_url":              product_url,
        "trigger_source":           TRIGGERED_BY,
        "segment_type":             "hot",
        "visitor_count":            visitor_count,
        "avg_behavioral_index":     avg_bi,
        "cvr_estimate":             cvr_estimate,
        "estimated_revenue_window": round(revenue_window, 2),
        "calibration_state":        calibration_state,
        "visitor_ids":              hot.get("visitor_ids", []),
        "auto_generated":           True,
        "expected_loss":            round(revenue_window, 2),
        "confidence":               round(float(cvr_estimate or 0), 6),
        "urgency":                  urgency,
        "supporting_signals":       ["HOT_SEGMENT"],
    }

    # 7. Create or dedup task
    try:
        task, task_created = create_task(
            db=db,
            shop_domain=shop_domain,
            candidate=candidate,
            triggered_by=TRIGGERED_BY,
        )
    except Exception as exc:
        log(f"create_task error shop={shop_domain} product={product_url}: {exc}")
        return "error"

    if task_created:
        log(
            f"TASK CREATED shop={shop_domain} product={product_url} "
            f"task_id={task.id} action={ACTION_TYPE} "
            f"hot_visitors={visitor_count} revenue_window=${revenue_window:.2f} "
            f"avg_bi={avg_bi} cvr={cvr_estimate} calibration={calibration_state}"
        )
    else:
        log(
            f"task dedup shop={shop_domain} product={product_url} "
            f"task_id={task.id} status={task.status} — using existing task"
        )

    # 8. Create or refresh the ActiveNudge — always, regardless of task dedup.
    #    The nudge refresh keeps the storefront copy current (visitor_count,
    #    expires_at) even when the task is already active.
    #    inventory_count is passed through so nudge_engine can add real scarcity
    #    copy when stock is low (inventory_count <= LOW_STOCK_THRESHOLD).
    try:
        nudge, nudge_created = create_or_refresh_nudge(
            db=db,
            shop_domain=shop_domain,
            product_url=product_url,
            action_type=ACTION_TYPE,
            trigger_source=TRIGGERED_BY,
            visitor_count=visitor_count,
            revenue_window=round(revenue_window, 2),
            calibration_state=calibration_state,
            action_task_id=task.id,
            inventory_count=inventory_count,
            holdout_pct=20,  # Enable causal measurement from day one
        )
        log(
            f"nudge {'CREATED' if nudge_created else 'refreshed'} "
            f"nudge_id={nudge.id} shop={shop_domain} product={product_url} "
            f"visitors={visitor_count} expires_at={nudge.expires_at.isoformat()}"
        )
    except Exception as exc:
        log(
            f"nudge create/refresh error shop={shop_domain} "
            f"product={product_url}: {exc} (task still created, non-fatal)"
        )

    return "created" if task_created else "refreshed"


# ---------------------------------------------------------------------------
# Main cycle
# ---------------------------------------------------------------------------

@cron_monitor(slug="segment_monitor_worker_cycle", interval_minutes=5, max_runtime_minutes=9)
def run_cycle() -> None:
    started_at = datetime.now(timezone.utc).replace(tzinfo=None)

    tasks_created    = 0
    tasks_refreshed  = 0
    tasks_cooldown   = 0
    products_below   = 0
    products_no_hot  = 0
    products_error   = 0
    shops_scanned    = 0
    products_scanned = 0
    last_error: str | None = None

    cycle_start = time.monotonic()
    db = SessionLocal()
    try:
        pro_shops = _get_pro_shops(db)
        batch, next_cursor = _batch_for_cycle(pro_shops)
        log(
            f"pro shops found: {len(pro_shops)} "
            f"(this cycle batch: {len(batch)}, next cursor: {next_cursor})"
        )

        if not pro_shops:
            log("no active Pro shops — nothing to scan")
            return

        from app.core.query_count_monitor import worker_scope as _worker_scope
        for shop_domain in batch:
            # Honor the time budget — stop cleanly rather than miss the heartbeat
            if time.monotonic() - cycle_start > CYCLE_TIME_BUDGET_S:
                log(f"time budget reached at shop {shops_scanned}/{len(batch)} — stopping")
                break
            shops_scanned += 1
            # Per-shop scan = active_products lookup + N _process_product
            # calls. worker_scope wraps the whole iteration so a future
            # N+1 regression in either path surfaces at runtime.
            with _worker_scope("segment_monitor.shop_scan", shop_domain):
                active_products = _get_active_products_for_shop(db, shop_domain)
                log(
                    f"shop={shop_domain} active_products={len(active_products)} "
                    f"(unique_visitors_24h >= {MIN_ACTIVE_VISITORS_24H})"
                )

                for product_url in active_products:
                    products_scanned += 1
                    result = _process_product(db, shop_domain, product_url)

                    if result == "created":
                        tasks_created += 1
                    elif result == "refreshed":
                        tasks_refreshed += 1
                    elif result == "cooldown":
                        tasks_cooldown += 1
                    elif result == "below_threshold":
                        products_below += 1
                    elif result == "no_hot_visitors":
                        products_no_hot += 1
                    elif result == "error":
                        products_error += 1
                        last_error = f"{shop_domain} | {product_url}"

        # Advance cursor only on successful batch completion so a crash
        # re-runs the same range rather than skipping shops.
        _save_cursor(next_cursor)

        log(
            f"cycle complete — "
            f"shops={shops_scanned} products_scanned={products_scanned} "
            f"tasks_created={tasks_created} tasks_refreshed={tasks_refreshed} "
            f"cooldown={tasks_cooldown} below_threshold={products_below} "
            f"no_hot_visitors={products_no_hot} errors={products_error}"
        )

    except Exception as exc:
        products_error += 1
        last_error = str(exc)
        log(f"cycle-level error: {exc}")
        raise

    finally:
        try:
            finished_at = datetime.now(timezone.utc).replace(tzinfo=None)
            duration_ms = int((finished_at - started_at).total_seconds() * 1000)
            entry = WorkerLog(
                worker_name=WORKER_NAME,
                started_at=started_at,
                finished_at=finished_at,
                shops_processed=shops_scanned,
                rows_written=tasks_created,
                errors=products_error,
                error_detail=last_error,
                duration_ms=duration_ms,
            )
            db.add(entry)

            # Also update worker_state.last_run_at so the health-check
            # layer (core/protection_state.py::_worker_pressure) sees a
            # fresh heartbeat. Previously this worker only wrote to
            # worker_log and left worker_state untouched, which made it
            # permanently appear stale and cascaded into protection_state
            # going CRITICAL → nudge_optimization_worker skipping its
            # cycles → more stale workers → loop.
            state = db.query(WorkerState).filter(
                WorkerState.worker_name == WORKER_NAME
            ).first()
            if state is None:
                state = WorkerState(worker_name=WORKER_NAME, last_run_at=finished_at)
                db.add(state)
            else:
                state.last_run_at = finished_at
            db.commit()
        except Exception as exc:
            log(f"worker_log/state write error (non-fatal): {exc}")
        db.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    log("worker started")
    while True:
        from app.core.distributed_lock import worker_lock
        from app.core.metrics import track_worker_cycle

        with worker_lock(WORKER_NAME, ttl_seconds=SLEEP_SECONDS + 60) as acquired:
            if not acquired:
                log("another instance holds the lock — skipping cycle")
            else:
                try:
                    with track_worker_cycle(WORKER_NAME):
                        run_cycle()
                except Exception as exc:
                    log(f"unhandled exception: {exc}")
                    raise
        log(f"sleeping {SLEEP_SECONDS}s")
        time.sleep(SLEEP_SECONDS)


if __name__ == "__main__":
    main()
