import os
from datetime import datetime, timezone
import logging

log = logging.getLogger("context_builder")

BASE_PATH = "/opt/wishspark"
BACKEND_PATH = f"{BASE_PATH}/backend/app"
DASHBOARD_PATH = f"{BASE_PATH}/dashboard/src/app"

OUTPUT_FILE = f"{BASE_PATH}/SERVER_CONTEXT.md"
AUTO_CONTEXT_FILE = f"{BASE_PATH}/docs/AUTO_CONTEXT.md"


def list_files(folder, ext=None):
    results = []
    for root, dirs, files in os.walk(folder):
        for f in files:
            if ext is None or f.endswith(ext):
                results.append(os.path.join(root, f).replace(BASE_PATH, ""))
    return sorted(results)


def extract_fastapi_routes():
    routes = []
    api_dir = f"{BACKEND_PATH}/api"
    if not os.path.exists(api_dir):
        return routes

    for root, dirs, files in os.walk(api_dir):
        for file in files:
            if file.endswith(".py"):
                path = os.path.join(root, file)
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        for line in f:
                            if "@router." in line:
                                routes.append(f"{path.replace(BASE_PATH, '')} :: {line.strip()}")
                except Exception as exc:
                    log.warning("context_builder: extract_fastapi_routes failed: %s", exc)
    return routes


def extract_dashboard_routes():
    routes = []
    if not os.path.exists(DASHBOARD_PATH):
        return routes

    for root, dirs, files in os.walk(DASHBOARD_PATH):
        for file in files:
            if file.startswith("page.") and file.endswith(("tsx", "jsx", "ts", "js")):
                rel = os.path.join(root, file).replace(DASHBOARD_PATH, "")
                route = (
                    rel.replace("/page.tsx", "")
                    .replace("/page.jsx", "")
                    .replace("/page.ts", "")
                    .replace("/page.js", "")
                ) or "/"
                routes.append(route)

    return sorted(set(routes))


def extract_docs():
    docs_path = f"{BASE_PATH}/docs"
    docs = []

    if not os.path.exists(docs_path):
        return docs

    for root, dirs, files in os.walk(docs_path):
        for f in files:
            if f.endswith(".md"):
                docs.append(os.path.join(root, f).replace(BASE_PATH, ""))

    return sorted(docs)


def build_server_context():
    backend_services = list_files(f"{BACKEND_PATH}/services", ".py")
    backend_models = list_files(f"{BACKEND_PATH}/models", ".py")
    backend_api = list_files(f"{BACKEND_PATH}/api", ".py")

    api_routes = extract_fastapi_routes()
    dashboard_routes = extract_dashboard_routes()
    docs_files = extract_docs()

    context = f"""# WishSpark Server Context
Auto-generated: {datetime.now(timezone.utc).replace(tzinfo=None).isoformat()} UTC

## Base Path
/opt/wishspark

## Stack
Backend: FastAPI
Frontend: Next.js
Process Manager: PM2

## Backend Structure

### API Modules
{chr(10).join(backend_api)}

### Services
{chr(10).join(backend_services)}

### Models
{chr(10).join(backend_models)}

## FastAPI Routes
{chr(10).join(api_routes)}

## Dashboard Routes
{chr(10).join(dashboard_routes)}

## Architecture Documents
{chr(10).join(docs_files)}

## Notes
This file is automatically generated by context_builder.py
Used by AI agents to understand server architecture.
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(context)


def build_auto_context():
    backend_services = list_files(f"{BACKEND_PATH}/services", ".py")
    backend_models = list_files(f"{BACKEND_PATH}/models", ".py")
    backend_api = list_files(f"{BACKEND_PATH}/api", ".py")
    dashboard_routes = extract_dashboard_routes()

    context = f"""# WishSpark Auto Context
Auto-generated: {datetime.now(timezone.utc).replace(tzinfo=None).isoformat()} UTC

## Project Root
/opt/wishspark

## Technical Summary
- Backend: FastAPI
- Frontend: Next.js dashboard
- Database: Postgres (docker)
- Cache: Redis (docker)
- Proxy: Traefik
- Process manager: PM2

## Backend API Modules
{chr(10).join(backend_api)}

## Backend Services
{chr(10).join(backend_services)}

## Backend Models
{chr(10).join(backend_models)}

## Dashboard Routes
{chr(10).join(dashboard_routes)}

## Agent Notes
- Read AGENTS.md first
- Use docs/CURRENT_STATE.md for stable project state
- Use docs/NEXT_STEPS.md for roadmap
- Use SERVER_CONTEXT.md and this file for auto-generated technical context
"""

    with open(AUTO_CONTEXT_FILE, "w", encoding="utf-8") as f:
        f.write(context)


def build_context():
    build_server_context()
    build_auto_context()
    print("SERVER_CONTEXT updated")
    print("AUTO_CONTEXT updated")


if __name__ == "__main__":
    build_context()

def extract_docs():
    docs_path = f"{BASE_PATH}/docs"
    docs = []
    for root, dirs, files in os.walk(docs_path):
        for f in files:
            if f.endswith(".md"):
                docs.append(os.path.join(root, f).replace(BASE_PATH, ""))
    return sorted(docs)
