"""
Opportunity signal API.

This file manages two distinct surfaces that share a name but differ in
data source, generation method, and product tier:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Surface A  —  OpportunitySignal table  (GET /opportunities and /pro)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by eight rule-based detectors in opportunity_engine.py (no AI,
no external calls, no Pro-tier data sources).  Results are cached in Redis
and the opportunity_signals table.

Lite route  GET /opportunities
  Returns diagnostic fields only: product_url, signal_type, signal_strength,
  explanation, detected_at, human_label.
  human_action is stripped at this boundary.

  explanation is a plain-English observation produced independently by the
  rule engine ("14 visitors browsed but didn't add to cart").  It is
  genuinely diagnostic — it stands on its own without the prescriptive layer.
  This is why the field-level Lite/Pro split is honest here.

Pro route   GET /opportunities/pro
  Identical to the Lite response PLUS human_action per signal.
  Backend-enforced via require_pro_plan (HTTP 403 for non-Pro shops).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Surface B  —  ProductOpportunity table  (GET /opportunities/top)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by the legacy intelligence worker (background job, AI-assisted
ranking).  The ProductOpportunity table has plan_required = "pro" for
every row — the data layer declares the entire surface Pro-only.

GET /opportunities/top is a Pro-only endpoint.
Backend-enforced via require_pro_plan (HTTP 403 for non-Pro shops).

Why there is no Lite split here (contrast with Surface A)
---------------------------------------------------------
1. The model marks every row plan_required = "pro".  Unlike OpportunitySignal
   (which has no plan_required column — it is Lite-safe by design), the
   ProductOpportunity table was built as a Pro intelligence product from the
   start.

2. The behavioral metrics a Lite merchant might want (avg_intent_score,
   hot_count, wishlist_count, avg_dwell_seconds) are already served to Lite
   callers through:
     /dashboard/overview → top_products (avg_intent_score, intent_level,
                           unique_visitors, wishlist_adds)
     /products/metrics   (views_24h, add_to_cart_24h, etc.)
   There is no net-new diagnostic information to expose.

3. The fields that are unique to this table (priority_score, recommended_action,
   opportunity_explanation) are outputs of the intelligence worker's Pro
   analysis — they explain the Pro ranking and recommendation.
   opportunity_explanation is NOT analogous to OpportunitySignal.explanation:
   it does not stand on its own as a plain observation; it is the intelligence
   worker's reasoning for its Pro-tier ranking decision.  Exposing it without
   the ranking context (priority_score) and the action (recommended_action)
   would be misleading, not diagnostic.

This surface flows to the frontend through /dashboard/overview/pro
(already enforced), not through a direct frontend call to this endpoint.

To enforce a new Pro endpoint with this same whole-Pro pattern:
  Add require_pro_plan as the only dependency.  No field stripping needed.
  Document in the module docstring why no Lite subset exists.
"""
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.core.deps import require_merchant_session, require_pro_session
from app.models.product_opportunity import ProductOpportunity
from app.services.opportunity_engine import get_or_refresh_signals

router = APIRouter()

# Fields that are safe to return to Lite subscribers (Surface A only).
# human_action is intentionally absent — it is prescriptive (Pro only).
# If new fields are added to the OpportunitySignal schema, audit them here
# before including them in the Lite response.
_LITE_SIGNAL_FIELDS = {
    "product_url",
    "signal_type",
    "signal_strength",
    "signal_confidence",
    "explanation",
    "detected_at",
    "human_label",
}


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Surface A — Lite route  GET /opportunities
#
# OpportunitySignal table. Diagnostic fields only.
# human_action is stripped at this boundary.
# ---------------------------------------------------------------------------
@router.get("/opportunities")
def opportunities(
    shop: str = Depends(require_merchant_session),
):
    """
    Lite opportunity signals — diagnostic fields only.

    Returns signals derived from the events table using eight rule-based
    detectors (no AI, no external calls).  Results are served from a
    three-level cache (Redis → DB → on-demand detection), so the detection
    queries run at most once every 5 minutes per shop.

    human_action is excluded from this response.
    Pro subscribers call /opportunities/pro to receive it.

    Lite boundary: signal_type, explanation, human_label, signal_strength
                   (what is happening — diagnostic)
    Pro boundary:  human_action
                   (what to do about it — prescriptive)
    """
    signals = get_or_refresh_signals(shop)
    # Strip prescriptive fields at the API boundary.
    # human_action is always computed by the detection engine but must not
    # be returned to Lite callers.  _LITE_SIGNAL_FIELDS is the allow-list.
    return [{k: v for k, v in sig.items() if k in _LITE_SIGNAL_FIELDS} for sig in signals]


# ---------------------------------------------------------------------------
# Surface A — Pro route  GET /opportunities/pro
#
# Full signal including human_action. Backend-enforced via require_pro_plan.
# ---------------------------------------------------------------------------
@router.get("/opportunities/pro")
def opportunities_pro(
    shop: str = Depends(require_pro_session),
):
    """
    Pro opportunity signals — full response including human_action per signal.

    Backend-enforced: require_pro_plan raises HTTP 403 if the shop does not
    have an active Pro plan (merchants.plan != "pro" or billing_active == False).
    API key and shop-domain validation are composed inside require_pro_plan.

    Returns the same signal list as /opportunities plus human_action — a
    plain-English prescriptive sentence telling the merchant what to do.

    Lite boundary: diagnostic fields (served by /opportunities)
    Pro boundary:  human_action per signal (served here — plan-enforced)
    """
    return get_or_refresh_signals(shop)


# ---------------------------------------------------------------------------
# Surface B — Pro route  GET /opportunities/top
#
# ProductOpportunity table. Entire endpoint is Pro-only.
# No Lite subset exists — see module docstring for full reasoning.
# ---------------------------------------------------------------------------
@router.get("/opportunities/top")
def top_opportunities(
    shop: str = Depends(require_pro_session),
    db: Session = Depends(get_db),
):
    """
    Pro intelligence opportunities — full response, backend-enforced.

    Returns ranked product opportunities from the legacy intelligence worker,
    ordered by priority_score descending.  All fields are Pro-tier: the model
    marks every row plan_required = "pro", and the fields unique to this
    table (priority_score, recommended_action, opportunity_explanation) are
    outputs of the Pro intelligence ranking — not standalone diagnostic facts.

    Backend-enforced: require_pro_plan raises HTTP 403 if the shop does not
    have an active Pro plan (merchants.plan != "pro" or billing_active == False).
    API key and shop-domain validation are composed inside require_pro_plan.

    This data also flows through /dashboard/overview/pro (already enforced)
    for the main frontend dashboard.  This dedicated endpoint serves external
    integrations or future Pro-specific dashboard sections.
    """
    results = (
        db.query(ProductOpportunity)
        .filter(ProductOpportunity.shop_domain == shop)
        .order_by(ProductOpportunity.priority_score.desc())
        .limit(20)
        .all()
    )

    return [
        {
            "product_url": r.product_url,
            "records": r.records,
            "avg_intent_score": r.avg_intent_score,
            "hot_count": r.hot_count,
            "wishlist_count": r.wishlist_count,
            "avg_dwell_seconds": r.avg_dwell_seconds,
            "avg_scroll_depth": r.avg_scroll_depth,
            "opportunity_type": r.opportunity_type,
            "priority_score": r.priority_score,
            "recommended_action": r.recommended_action,
            "opportunity_explanation": r.opportunity_explanation,
            "plan_required": r.plan_required,
        }
        for r in results
    ]
