"""add primary_currency and iana_timezone to merchants

Revision ID: b86443ac80a1
Revises: zzz8_float_money_to_numeric
Create Date: 2026-04-16 07:01:13.298792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86443ac80a1'
down_revision: Union[str, Sequence[str], None] = 'zzz8_float_money_to_numeric'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('primary_currency', sa.String(length=8), nullable=True))
    op.add_column('merchants', sa.Column('iana_timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'iana_timezone')
    op.drop_column('merchants', 'primary_currency')
    # ### end Alembic commands ###
